### ISSUE TITLE
Questions about DDPM timesteps 

### ISSUE THREAD

**Issue by tryhiseyyysum** [neu-vi/MARDM#3]
Hi, I wonder why you use 50 timesteps to train the DDPM-based Diffusion model, instead of 1000 timesteps? Does it really work using only 50 timesteps to add noise? In my opinion, 50 timesteps is far from getting a gaussian noise. So I'm really curious about how you make this work?

**Comment by cr8br0ze** [comment]
Hi, thank you for your interest in our work. We use 50 steps to train and sample because 1. the speed of generation (1000 steps is around 20x slower than 50 steps), 2. following previous works which shows models can generate same or even better quality with less steps.
Using less timesteps to train in text-to-motion generation first comes from [MDM](https://github.com/GuyTevet/motion-diffusion-model), where they use 50 steps instead of 1000 steps to train and sample (and works better than 1000 steps).
Recall for DDPM, the interpolation function is $\mathbf{x}_t = \sqrt{\bar{\alpha}_t}\mathbf{x}_0 + \sqrt{1 - \bar{\alpha}_t}\boldsymbol{\epsilon}$. If we set total timesteps as T=50, at time 50, we will get  $\mathbf{x}_T = 0\times\mathbf{x}_0 + 1\times\boldsymbol{\epsilon} = \boldsymbol{\epsilon}$, so it still converges to a guassian noise. Reducing steps should only affect the step sizes which is the beta schedule ($\beta$ and $\alpha_t = 1 - \beta_t$). So, naively, can think in this way, compared to 1000 steps which take more but smaller steps to generate, 50 steps take less but larger step size in each step.
